certmanager:
  issuer: letsencrypt-prod-issuer
  email: webmaster@lidonation.com
  server: https://acme-staging-v02.api.letsencrypt.org/directory

GOOGLE_CLOUD_KEY_FILE:

namespace: catalyst

network: mainnet

image:
  pullSecret: 'deploy-token-lidonation'
  pullPolicy: IfNotPresent
  tag: latest

DEPLOY_INFRA: False

services:
  redis:
    secret:
      REDIS_PASSWORD:
  api_db:
    persistence:
      enabled: true
      size: 8Gi
    secret:
      POSTGRESQL_DB: catalyst
      POSTGRESQL_USERNAME: catalyst
      POSTGRESQL_PASSWORD:
      POSTGRESQL_POSTGRES_PASSWORD:
  queue:
    replicaCount: 2
  api:
    image:
      repository: registry.raddcreative.io/lidonation/catalyst-proposal-api/api.projectcatalyst.org
    ingress:
      controller:
        headers:
          HTTPS: "on"
      annotations: {
        kubernetes.io/ingress.class: nginx,
        nginx.ingress.kubernetes.io/ssl-redirect: "true",
        ingress.kubernetes.io/rewrite-target: /,
        nginx.ingress.kubernetes.io/from-to-www-redirect: "true",
        cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
      }
      hosts:
        - api.projectcatalyst.org
      tls:
        - secretName: api-projectcatalyst-tls
          hosts:
            - api.projectcatalyst.org
    replicaCount: 2
    config: {
      APP_NAME: 'Catalyst Proposal API',
      APP_ENV: production,
      APP_DEBUG: "false",
      APP_DIR: "/var/www",
      APP_LOG_LEVEL: "warning",
      APP_URL: "https://api.projectcatalyst.org",
      ANALYTICS_ID: "",
      CACHE_DRIVER: redis,
      CLOUDFLARE_TOKEN: "",


      DEPLOYMENT: production,
      DB_CONNECTION: pgsqlWeb,
      DB_SYNC_DB_CONNECTION: pgsqlDbSync,

      POSTGRESQL_DB_HOST: lidolovelace-web-db-postgresql,
      POSTGRESQL_DB: lidoweb,
      POSTGRESQL_USER: lnation,

      KUBERNETES_NAMESPACE: lidonation,

      LOG_CHANNEL: stack,

      MAIL_DRIVER: smtp,
      MAIL_HOST: smtp.mailtrap.io,
      MAIL_PORT: 2525,

      MAIL_FROM_ADDRESS: 'team@lidonation.com',
      MAIL_FROM_NAME: 'Project Catalyst API',
      MEDIA_DISK: 'gcs',

      MAILCHIMP_APIKEY: '',
      MEILISEARCH_HOST: 'catalyst-api-search-service:7700',
      MEILI_ENV: production,

      PHP_OPCACHE_ENABLE: 1,
      PHP_OPCACHE_SAVE_COMMENTS: 1,
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0,
      PHP_MEMORY_LIMIT: 1024M,
      PHP_DISABLE_FUNCTIONS: "passthru,shell_exec,show_source,symlink,system",

      PUSHER_CLUSTER:  us2,

      QUEUE_DRIVER: redis,
      QUEUE_CONNECTION: redis,
      QUEUE_NAMES: "default",

      REDIS_PREFIX: "lido",

      REDIS_HOST: redis-master,
      REDIS_PORT: 6379,

      RESTORE_DB: true,
      RUN_SCHEDULER: true,

      SCOUT_PREFIX: ca__,

      SET_PERMISSIONS: false,

      SESSION_DRIVER: redis,
      SESSION_CONNECTION: session,
      STRIPE_MODEL: App\User,
      STRIPE_KEY: "",

      STRIPE_SECRET: "",

      TELESCOPE_ENABLED: "false"
    }
    secret:
      app_key:
      DEEPL_AUTH_KEY:
      MAIL_PASSWORD: 'password'
      MAIL_USERNAME: 'username'
    persistence:
      size: 20Gi
      storageClass: ssd
      accessMode: ReadWriteMany
      subPath: "storage"
      mountPath: "/var/www/storage"

  tolerations:
    - key: "tier"
      operator: "Equal"
      value: "t2"
    - key: "tier"
      operator: "Equal"
      value: "t0"
