version: "3.8"

services:
    search-service:
        container_name: search
        image: getmeili/meilisearch:v0.23.1
        networks:
            - catalyst-network
        ports:
            - "7700:7700"
        environment:
            MEILI_MASTER_KEY: v8hlDV0yMAHHlIurYupj
            MEILI_ENV: development
    pgAdmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        networks:
            - catalyst-network
        environment:
            - PGADMIN_DEFAULT_EMAIL=hello@lidonation.com
            - PGADMIN_DEFAULT_PASSWORD=alj2340aaALJAF2341408AUUZLJK
        ports:
            - "8888:80"
    redis-service:
        image: redis:7.0-rc-alpine
        command: [ sh, -c, "rm -f /data/dump.rdb && redis-server --save ''" ]
        networks:
            - catalyst-network
    db-service:
        image: postgres:14.2-alpine3.15
        container_name: catalyst_db
        environment:
            - POSTGRES_LOGGING=true
            - POSTGRES_DB=catalyst
            - POSTGRES_PASSWORD=ASLJ023470AlserLFH
            - POSTGRES_USER=catalyst
            - POSTGRES_POSTGRES_PASSWORD=alj2340aaALJAF2341408AUUZLJK
        ports:
            - "5436:5432"
        restart: on-failure
        networks:
            - catalyst-network
        volumes:
            - type: volume
              source: catalyst_db
              target: /var/lib/postgresql/data
              volume:
                  nocopy: true
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
    catalyst-api-api-service:
        image: registry.raddcreative.io/lidonation/lidonation/api.projectcatalyst.org
        container_name: api
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        networks:
            - catalyst-network
        depends_on:
            - search-service
            - db-service
            - redis-service
        env_file:
            - ./src/app.env
        environment:
            APP_URL: 'http://localhost:8080'
            APP_SETUP: "true"
            PHP_OPCACHE_ENABLE: 0
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            CONTAINER_ROLE: "app"
            DB_CONNECTION: pgsql
            FPM_SERVICE: '127.0.0.1'
            MEILISEARCH_KEY: v8hlDV0yMAHHlIurYupj
            MEILISEARCH_HOST: "search-service:7700"
            POSTGRESQL_DB_HOST: "db-service"
            POSTGRESQL_DB: catalyst
            POSTGRESQL_USER: catalyst
            POSTGRESQL_PASSWORD: ASLJ023470AlserLFH
            MEDIA_DISK: public
            TELESCOPE_USE_DARK_THEME: "true"
        build:
            dockerfile: Dockerfile
            context: ./
            args:
                WWWUSER: ${WWWUSER:-$UID}
        expose:
            -   9000
        volumes:
            - ./src:/var/www
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www
            - ./build/rootfs/etc/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - catalyst-network
volumes:
    catalyst_db:

networks:
    catalyst-network:
        driver: bridge