apiVersion: v1
stringData:
  APP_KEY: {{ .Values.services.api.secret.app_key }}
  MAIL_USERNAME: {{ .Values.services.api.secret.MAIL_USERNAME }}
  MAIL_PASSWORD: {{ .Values.services.api.secret.MAIL_PASSWORD }}
  MEILISEARCH_KEY: {{ .Values.services.api.secret.MEILISEARCH_KEY }}
  POSTGRESQL_PASSWORD: {{ .Values.services.api_db.secret.POSTGRESQL_PASSWORD }}
  REDIS_PASSWORD: {{ .Values.services.redis.secret.REDIS_PASSWORD }}
kind: Secret
metadata:
  name: "{{ $.Chart.Name }}-secrets"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
type: Opaque