version: "3.8"

services:
    search-service:
        container_name: search
        image: getmeili/meilisearch:v0.23.1
        ports:
            - "7700:7700"
        environment:
            MEILI_MASTER_KEY: v8hlDV0yMAHHlIurYupj
            MEILI_ENV: development
    pgAdmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=hello@lidonation.com
            - PGADMIN_DEFAULT_PASSWORD=alj2340aaALJAF2341408AUUZLJK
        ports:
            - "8888:80"
    redis:
        image: redis:7.0-rc-alpine
        command: [ sh, -c, "rm -f /data/dump.rdb && redis-server --save ''" ]
    db-service:
        image: postgres:14.2-alpine3.15
        container_name: db
        environment:
            - POSTGRES_LOGGING=true
            - POSTGRES_DB=lidoweb
            - POSTGRES_PASSWORD=ASLJ023470AlserLFH
            - POSTGRES_USER=lido
            - POSTGRES_POSTGRES_PASSWORD=alj2340aaALJAF2341408AUUZLJK
        ports:
            - "5436:5432"
        restart: on-failure
        volumes:
            - type: volume
              source: web_db
              target: /var/lib/postgresql/data
              volume:
                  nocopy: true
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
    api-service:
        image: registry.raddcreative.io/lidonation/lidonation/www.lidonation.com
        container_name: api
        restart: unless-stopped
        depends_on:
            - search
            - db
            - redis
        env_file:
            - ./src/app.env
        environment:
            APP_URL: 'http://localhost:8080'
            APP_SETUP: "true"
            PHP_OPCACHE_ENABLE: 0
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            CONTAINER_ROLE: "app"
            DB_CONNECTION: db
            FPM_SERVICE: '127.0.0.1'
            MEILISEARCH_KEY: v8hlDV0yMAHHlIurYupj
            MEILISEARCH_HOST: "search-service:7700"
            POSTGRESQL_DB_HOST: "db-service"
            POSTGRESQL_DB: catalyst
            POSTGRESQL_USER: catalyst
            POSTGRESQL_PASSWORD: ASLJ023470AlserLFH
            MEDIA_DISK: public
            TELESCOPE_USE_DARK_THEME: "true"
        build:
            context: ./
            args: {}
        ports:
            - "8080:8080"
        volumes:
            - ./src/www.lidonation.com/var/www:/var/www
            - ./data/www/data:/data
            - ./build/web/etc/nginx/resolver_dev.conf:/etc/nginx/resolver.conf
volumes:
    web_db:
